import type { SourceKindValue } from "@/lib/document-prep";

export type CorpusDocument = {
  id: string;
  title: string;
  sourceKind: SourceKindValue;
  text: string;
};

const ragOverview = `Retrieval-augmented generation, or RAG, is a system pattern that connects a language model to external evidence before an answer is produced. The practical goal is not simply to add more text to a prompt. The goal is to make the model operate from the right evidence at the right moment, with a trail that engineers and users can inspect. In a production setting this matters because the model alone cannot guarantee freshness, policy alignment, or organization-specific correctness. A RAG system improves these properties by adding a retrieval layer between the user question and the model response.

A complete RAG pipeline is easier to understand if it is split into phases. The first phase is document preparation. Raw source material is collected, ingested, cleaned, annotated, chunked, embedded, and indexed. The second phase is query-time retrieval. A user question is normalized, embedded, matched against the index, narrowed into a candidate set, filtered, reranked, and packed into a final context. The third phase is grounded generation. The model receives the final evidence package together with instructions that it must answer only from that evidence. This breakdown matters because different failure modes appear in different phases.

Many newcomers assume RAG is mostly a prompt engineering technique. That assumption is weak because most serious failures happen before the prompt ever reaches the model. If ingestion is inconsistent, if formatting noise is preserved, if metadata is absent, if chunk boundaries are poor, or if the retriever never surfaces the right passage, then the final answer will fail no matter how carefully the prompt is written. A useful way to think about RAG is therefore as an evidence supply chain. Prompting is only the final delivery step. Everything upstream determines whether the right evidence is even available to deliver.

The business reason RAG exists is straightforward. Most organizations already have valuable knowledge in documentation, policies, runbooks, support notes, design records, and research summaries. These materials change far more frequently than a foundation model can be retrained. A model-only assistant will therefore drift behind operational reality. It may produce plausible answers that conflict with the current handbook, the latest incident process, or the current pricing policy. RAG addresses this by retrieving from authoritative sources at question time instead of relying on frozen pretraining knowledge as the only source of truth.

Source authority is central to the design. Not every document should be treated as equally trustworthy. A production corpus may contain published policies, draft notes, archived documents, duplicated wiki pages, and role-restricted manuals. If the retrieval system cannot distinguish among these categories, the answer generator may combine contradictory evidence or lean on outdated guidance. This is why source selection and metadata enrichment are first-class stages in mature RAG systems. The pipeline is not merely asking what text exists. It is asking which text should be considered valid, visible, recent, and usable for the task at hand.

Observability is another defining feature. A model answer without evidence is hard to debug. A RAG answer with visible retrieved chunks can be audited stage by stage. Engineers can inspect whether the right source document entered the corpus, whether cleaning removed useful structure, whether chunking preserved meaning, whether embeddings produced separable vectors, whether the retriever surfaced the right candidates, and whether context construction preserved the strongest evidence. This is how teams improve the system systematically. Without observability, they often blame the model for defects that actually originated in preparation or retrieval.

A strong RAG system also needs a clear failure policy. If the system cannot retrieve supporting evidence, the answer generator should not improvise. In high-trust domains, abstention is preferable to unsupported fluency. This product choice shapes prompt design, ranking thresholds, filtering rules, and evaluation. The pipeline should be optimized not only for answer rate, but for groundedness. The best answer is not always the longest or the most confident. It is the one that stays within what the retrieved evidence can support and clearly signals when support is missing.

Educational tools often hide these realities by using one short document and one trivial search step. That teaches the mechanism but not the engineering tradeoffs. A more useful learning setup uses multiple documents with different shapes and different retrieval intent. One document may explain the architecture, another may focus on chunking, another on vector indexing, and another on query-time evaluation. With a multi-document corpus, learners can see that retrieval must choose among sources, not just within one source. That shift is important because it makes indexing, provenance, filtering, and context construction feel like necessary system components rather than optional embellishments.

Evaluation closes the loop. A production RAG system should be judged on whether the right evidence appears in the top-k candidates, whether the final context contains the passages needed for the answer, whether the generated response stays grounded, and whether users can verify the source support themselves. Latency, cost, freshness, and permission safety also matter. These are system-level metrics, not model-only metrics. The central lesson is that RAG quality is an engineering property emerging from many decisions across the pipeline, not from one magic model call.

For that reason, the best mental model is simple: document preparation shapes what can be retrieved, retrieval shapes what can be answered, and grounded generation shapes how safely the answer is expressed. Every stage narrows uncertainty. Every stage can also introduce failure if handled casually. A production RAG tool should therefore expose the stages directly so that users learn how evidence moves through the system rather than treating retrieval as a black box between a question and an answer.`;

const chunkingGuide = `Chunking is the stage where a document is split into retrieval units. It sounds like a mechanical preprocessing step, but in practice it is one of the strongest levers in the whole pipeline. A retriever can only search the units it has available, so chunking determines the size, coherence, and granularity of the evidence the system can ever return. If chunking is too coarse, retrieval becomes vague. If it is too fine, retrieval becomes brittle. The chunker is therefore not just formatting text. It is defining the search surface of the knowledge base.

Chunk size is the first major tradeoff. Small chunks often improve precision because each chunk contains fewer unrelated ideas. When a query asks about one narrow concept, a compact chunk can produce a cleaner similarity signal than a large paragraph block that mixes several topics together. However, very small chunks also strip away local context. A sentence may mention an important term but depend on the surrounding explanation to be interpretable. If retrieval returns a fragment without its scope, condition, or exception, the generation model may produce an answer that is technically grounded in a fragment yet operationally misleading.

Large chunks preserve more local context and are more likely to be self-contained. They can carry a definition together with its example, a policy together with its exception, or a troubleshooting step together with its warning. This often helps the model answer more accurately because the evidence contains more of the surrounding meaning. The cost is reduced precision. Large chunks can blur together unrelated concepts, making it harder for the embedding and ranking layers to identify which part of the chunk is truly relevant to the question. Large chunks also consume more prompt budget downstream, leaving less room for other evidence.

Overlap is the second major control. Without overlap, information that lands on a boundary can be split in a way that weakens both resulting chunks. A concept that begins at the end of one chunk and completes at the start of the next may never be represented cleanly in either place. Overlap addresses this by repeating some material across neighboring chunks. The benefit is continuity. The cost is redundancy. More overlap means more storage, more near-duplicate candidates during retrieval, and more work during context construction to avoid wasting space on repetitive evidence. In practice, moderate overlap is often useful, but aggressive overlap can make the corpus noisier rather than better.

The best chunking strategy depends heavily on document shape. Long-form essays often benefit from recursive chunking because paragraph boundaries already carry meaning. Structured reference guides often benefit from markdown-aware chunking because headings and list sections define topical units. Short notes may work with character or recursive chunking depending on how uneven their formatting is. Token-aware chunking becomes important when downstream context windows are tight and the team wants chunk sizes to align with how the generation model actually counts input. There is no universal best chunker. There is only a chunker that fits the structure and use case of the corpus.

Recursive chunking is popular because it tries to preserve structure before enforcing hard size limits. Instead of chopping the document at a fixed offset, it attempts to split at higher-level separators first, such as double newlines, then line breaks, then sentence-like boundaries, and only finally within tighter spans if needed. This often yields chunks that look more natural to a reader and more coherent to a retriever. The downside is that recursive boundaries can vary in shape, which may make corpus behavior less predictable if the underlying source formatting is inconsistent. Good cleaning and stable source structure help recursive chunking perform well.

Token-aware chunking uses model tokens rather than characters as the unit of size. That matters because characters are only a rough proxy for what a model can actually accept in context. A short symbol-dense passage can be surprisingly expensive in tokens, while a longer plain-language passage may fit comfortably. Token-aware chunking is useful when the team wants precise control over downstream context packing and generation costs. It is also a better match for teaching users how chunk size interacts with actual model limits rather than visual text length alone.

Markdown-aware chunking is especially useful for technical content. Headings, subheadings, lists, and fenced sections often already express how the author grouped concepts. Preserving those groups improves retrieval because the resulting chunks align with the intended semantic sections of the document. If the chunker ignores headings or if cleaning strips them too early, the system loses a valuable signal. A question about vector indexes should ideally retrieve the section under that heading, not a random slice across two unrelated sections merely because the fixed window happened to land there.

Chunking must also be evaluated against expected user behavior. A system serving narrow fact lookup queries may benefit from smaller, more focused chunks. A system serving conceptual questions may need larger chunks so the generation model sees the surrounding rationale and caveats. In many production systems, teams discover that chunking should not be static across every source. Policies, engineering guides, release notes, and short KB snippets may each deserve different defaults. That is why metadata-driven chunking policies and corpus-aware recommendations become useful once the system grows beyond a toy demo.

The most practical lesson is that chunking should be observable. Users should be able to see how one strategy differs from another, how overlap changes boundaries, and how those boundaries affect retrieval results. When chunking is visible, learners can connect a control change to a retrieval change. When it is hidden, chunking is reduced to folklore. A production-quality learning tool should therefore treat chunking as an experimental stage with concrete inputs, outputs, and downstream consequences.`;

const vectorSearchNotes = `Embeddings turn text into vectors, but a vector index is what turns those vectors into a searchable system. Once chunk vectors exist, they need to be stored in a structure that supports comparison against future query vectors and preserves a reliable mapping back to the source passages that created them. Without the index, the vectors are only representations. With the index, they become searchable corpus state. This distinction matters because many explanations of RAG jump directly from embeddings to search results and skip the storage layer that actually makes retrieval operational.

The first job of the index is provenance. Every vector must remain linked to the document, local chunk, and source range that produced it. This mapping is what makes later filtering, citation rendering, and debugging possible. If the system retrieves a high-scoring vector but cannot explain which chunk it came from, the result is operationally weak. Engineers need to know what text matched, where it lived in the source corpus, and what metadata was attached to it. A production index is therefore not only a vector store. It is a vector store plus retrieval-critical metadata alignment.

The second job of the index is search behavior. In a simple educational setup, the index can be a flat array scanned at query time. That makes the mechanism easy to understand because every stored vector is scored directly. In larger production systems, brute-force search becomes too expensive, so approximate nearest-neighbor structures are introduced. These structures trade exactness for speed by narrowing which vectors are compared. The conceptual lesson remains the same: the index defines how the query meets the stored corpus vectors. Scale changes the mechanics, but not the core contract.

Distance metrics are part of that contract. Cosine similarity is common because it compares directional similarity between vectors and works well when vectors are normalized or when magnitude is less important than orientation. Dot product is also used in many systems, especially when the embedding model and index are designed for that metric. The same corpus and the same embedding model can yield different rankings under different metrics. For that reason, the metric should not be treated as an invisible implementation detail. It is a retrieval choice that changes result ordering and therefore changes which evidence reaches the generator.

Index build workflows are just as important as index search. Corpora change over time. New documents are added, existing passages are revised, stale chunks should be removed, and metadata policies can shift. If the index is not rebuilt or incrementally updated correctly, retrieval drifts away from the real corpus. A system may return outdated passages, duplicate chunks, or vectors that no longer match the latest text. This is why indexing is often part of a larger synchronization pipeline in production. Retrieval quality depends not only on the index algorithm, but also on whether the index accurately reflects the current state of the source data.

Per-document chunk counts are a simple but useful diagnostic. A long document may contribute dozens of chunks while a short document contributes only a few. If one source dominates the index with many similar chunks, that source can crowd the candidate pool and reduce result diversity. Engineers who inspect document-level index distribution can often detect this problem early. A corpus that looks balanced in document count may still be unbalanced in chunk count. When retrieval seems to prefer one source too often, the explanation is sometimes not a ranking bug but an index composition issue.

Metadata support becomes more important as the index grows. Production systems rarely search every indexed vector equally for every user and every query. Some questions should search only technical runbooks, some should search only policy documents, and some should exclude archived materials or role-restricted content. That means the index must either support filtering directly or preserve enough metadata that a filtering stage can narrow candidates immediately after retrieval. If metadata is inconsistent or missing, the index may be technically correct while still being operationally unsafe or irrelevant.

Another misconception is that a sophisticated index can compensate for weak upstream preparation. It cannot. If chunking created poor retrieval units, the index faithfully stores poor retrieval units. If the embedding model fails to represent domain meaning well, the index faithfully stores weak representations. The index amplifies whatever quality enters it. Strong document preparation and strong embeddings make the index useful. Weak preparation makes the index an efficient way to search the wrong representation. This is why indexing should be explained as one link in the pipeline rather than as a standalone remedy.

Educational tools should therefore visualize the index as searchable inventory. How many chunk vectors are stored? Which documents contributed them? What metric will compare them? What vector dimension is being used? What index slots map to which source passages? When learners can see these details, retrieval stops looking magical. They understand that semantic search is simply the process of comparing a query vector against this explicit indexed collection and then following the provenance links back to the original text. That is the right conceptual bridge from document preparation to query-time retrieval.

In mature systems, the index is also where product constraints show up most clearly. Latency budgets, memory limits, freshness requirements, and permission models all influence index design. A support assistant that must answer quickly from current runbooks may choose a different index strategy than a research assistant that can tolerate slower, broader search across a larger archive. This is why indexing deserves to be a first-class stage in a production RAG learning tool. It is not just infrastructure. It is where prepared documents become retrievable system state.`;

const retrievalOpsDoc = `Query-time retrieval is where a RAG system decides what evidence a user question deserves. By the time this phase begins, the corpus has already been ingested, cleaned, chunked, embedded, and indexed. The retrieval pipeline now has to normalize the query, search the indexed corpus, rank candidate chunks, filter undesirable matches, optionally rerank the survivors, and assemble the final context passed to generation. This phase matters because even a well-prepared corpus is useless if the system cannot reliably surface the passages that actually answer the question.

Query processing is the first control surface. At minimum, the system should normalize whitespace and preserve a stable lowered form so superficial formatting does not distort retrieval. More advanced systems may classify the question type, detect entities, expand acronyms, or distinguish lookup queries from exploratory queries. That distinction matters. A factual lookup may need narrow precision and strong filtering. A broader conceptual question may benefit from greater candidate diversity before reranking. Query processing is therefore the stage where the retrieval system interprets intent before touching the vector index.

Candidate retrieval is usually the first scoring pass. The system embeds the processed query and compares it against the indexed chunk vectors. The immediate goal is not always to find the final context directly. In many systems the first pass is optimized for speed and recall, meaning it tries to gather a plausible working set of candidates quickly. If the system is too strict here, relevant evidence may never enter the pool. If it is too loose, downstream ranking and context construction become noisy. The top-k setting is a simple visible control for this tradeoff, but in production the effective cutoff is often shaped by latency budgets and downstream reranking cost.

Filtering comes next because vector similarity alone is not enough. A high-scoring chunk may still be unsuitable. It may be too short to support an answer, too old for the task, from the wrong source category, or lacking explicit lexical overlap needed for a narrow query. Score thresholds, minimum length rules, metadata constraints, and keyword overlap checks are all examples of filters that improve trust. These filters do not replace retrieval; they refine it. Their job is to remove candidates that are technically similar but operationally weak as evidence.

Reranking is often the stage that most clearly separates a simple demo from a production pipeline. First-pass retrieval is usually fast and approximate in spirit, even if the underlying vector comparisons are exact. Reranking applies a stronger scoring method to the already narrowed candidate set. This can use a cross-encoder, a stronger language model, or a domain-specific heuristic. The point is not to search the whole corpus again. The point is to improve ordering quality once a manageable candidate set exists. Many systems see noticeable grounded-answer improvements from reranking because the final context starts with the strongest evidence rather than merely the fastest approximate matches.

Context construction is where the retrieved evidence is turned into the actual prompt payload. This step is often underestimated. The best candidates are not always simply concatenated in ranked order. The system may need to deduplicate overlapping passages, keep evidence from the same document adjacent, preserve source diversity, or reserve context space for multiple subtopics present in one question. Good context construction is about evidence usability. The model should receive a context that is readable, non-redundant, provenance-aware, and sized appropriately for the chosen generation model.

Citations depend on this provenance-aware context assembly. If the final answer is meant to be inspectable, the system should retain source labels and chunk identities throughout retrieval and context packing. This allows the answer interface to show users exactly which documents and which passages supported the response. Citations also help engineers debug ranking failures. When the answer is wrong, the presence or absence of the right chunk in the final context often reveals whether the issue came from retrieval, filtering, reranking, or generation. Without provenance, every failure looks like a model failure even when it is not.

Evaluation and monitoring close the loop. Teams need to know whether the right evidence appears in the candidate pool, whether filters are too aggressive, whether reranking is improving or harming final relevance, whether context packing is omitting critical support, and whether the generated answers remain grounded in the final evidence set. Monitoring also matters because retrieval behavior can drift as the corpus changes. New documents can introduce repeated terminology, stale documents can stay indexed too long, and question distributions can shift as users adopt the product. A production RAG system should therefore treat retrieval quality as a monitored property, not as a one-time setup decision.

A multi-document corpus makes these query-time phases far more realistic. With one document, the retriever usually only needs to find the right location within a single source. With several documents, it must first surface the right source, then the right chunk within that source, and then decide whether supporting context from other documents should also be included. That is where candidate retrieval, filtering, provenance tracking, and context construction become visibly useful. The system is no longer selecting among chunks in a vacuum. It is navigating a corpus with competing sources and different intents.

The main lesson is that query-time retrieval is not one black-box search call. It is a chain of explicit decisions about interpretation, scoring, pruning, ordering, and evidence assembly. A strong educational RAG tool should expose these steps directly so users can see how one question turns into a final evidence package. That visibility helps learners understand why production RAG is a pipeline design problem. The answer is only as good as the retrieved evidence, and the retrieved evidence is only as good as the sequence of decisions that selected it.`;

export const demoCorpus: CorpusDocument[] = [
  {
    id: "rag-overview",
    title: "RAG Overview",
    sourceKind: "essay",
    text: ragOverview,
  },
  {
    id: "chunking-guide",
    title: "Chunking Guide",
    sourceKind: "essay",
    text: chunkingGuide,
  },
  {
    id: "vector-search-notes",
    title: "Vector Search Notes",
    sourceKind: "essay",
    text: vectorSearchNotes,
  },
  {
    id: "retrieval-operations",
    title: "Retrieval Operations",
    sourceKind: "essay",
    text: retrievalOpsDoc,
  },
];

export const demoCorpusById = Object.fromEntries(demoCorpus.map((document) => [document.id, document])) as Record<string, CorpusDocument>;
